import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './css/globals.css'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'CSS Founder | Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/admin/favicon.svg' type='image/svg+xml' />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var p='/admin';var f=window.fetch.bind(window);window.fetch=function(i,n){function r(u){try{var x=new URL(u,location.origin);if(x.origin!==location.origin)return u;if(x.pathname.indexOf(p+'/')===0)return u;if(x.pathname.indexOf('/api/')===0||x.pathname==='/api'||x.pathname.indexOf('/images/')===0){x.pathname=p+x.pathname;return x.pathname+x.search+x.hash}}catch(e){}return u}if(typeof i==='string')return f(r(i),n);if(typeof Request!=='undefined'&&i instanceof Request){var nu=r(i.url);if(nu!==i.url)return f(new Request(nu,i),n)}return f(i,n)}})();`,
          }}
        />
        {/* {typeof window !== 'undefined' && <ThemeModeScript />} */}
      </head>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
